# Generated by Django 3.2.4 on 2021-06-10 17:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='post',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('COMMERCIAL', 'COMMERCIAL'), ('SUPPORT', 'SUPPORT')], default='ADMIN', max_length=20),
        ),
    ]
